apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'


android {
  compileSdkVersion rootProject.ext.compileSdkVersion

  namespace = "com.raywenderlich.android.opinionator"
  compileSdk = 34

  defaultConfig {
    applicationId "com.raywenderlich.android.opinionator"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  kotlinOptions {
    jvmTarget = "1.8"
//    freeCompilerArgs += "-Xallow-jvm-ir-dependencies"
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  buildFeatures {
    compose true

    // Disable unused AGP features
    buildConfig false
    aidl false
    renderScript false
    resValues false
    shaders false
  }
  composeOptions {
    kotlinCompilerExtensionVersion = "1.5.11"
  }
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])

  // Kotlin
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

  // Support Libraries
  implementation 'androidx.appcompat:appcompat:1.3.0'
  implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

  // Testing Dependencies
  testImplementation 'junit:junit:4.13.2'
  androidTestImplementation 'androidx.test.ext:junit:1.2.1'
  androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

  // TUTORIAL DEPENDENCIES HERE
//  implementation "androidx.activity:activity-compose:1.3.0-rc01"
  implementation "androidx.activity:activity-compose:1.8.2"
  implementation "androidx.compose.ui:ui:$compose_version"
  implementation "androidx.compose.material:material:$compose_version"
  implementation "androidx.compose.material:material-icons-extended:$compose_version"
  implementation "androidx.compose.ui:ui-tooling:$compose_version"
  implementation "androidx.compose.ui:ui-util:$compose_version"
  implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
  implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
  implementation "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
  implementation "com.google.accompanist:accompanist-pager:0.10.0"
  implementation "com.google.accompanist:accompanist-pager-indicators:0.10.0"
  implementation("com.google.code.findbugs:jsr305:3.0.2")

  implementation platform('androidx.compose:compose-bom:2024.01.00')
  implementation "androidx.compose.ui:ui"
  implementation "androidx.compose.material:material"


}
