apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'


android {
  compileSdkVersion 33
  defaultConfig {
    applicationId "com.raywenderlich.colorcam"
    minSdkVersion 21
    targetSdkVersion 33
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  //Kotlin
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

  //Appcompat
  implementation "androidx.appcompat:appcompat:$appcompat_version"

  //Ktx
  implementation "androidx.core:core-ktx:$ktx_version"

  //Constraint layout
  implementation "androidx.constraintlayout:constraintlayout:$constraint_layout_version"


  //Anko
//  implementation "org.jetbrains.kotlin:kotlin-stdlib:1.6.21"
//  implementation "org.jetbrains.anko:anko:0.10.8"

  //Material design
  implementation "com.google.android.material:material:$material_version"

  //CameraX
  implementation "androidx.camera:camera-core:$camerax_version"
  implementation "androidx.camera:camera-camera2:$camerax_version"
  implementation "androidx.camera:camera-extensions:$camerax_extension"


}
